### ISSUE TITLE
yarn package does not contain the sources

### ISSUE THREAD

**Issue by kreba** [ccwukong/react-cam#1]
I was delighted to stumble upon this gem of a library :)
Sadly, it does not deliver any source code via yarnpkg.
Thought I'd let you know :)

**Comment by ccwukong** [comment]
@kreba Thanks, I will fix it.

**Comment by ccwukong** [comment]
@kreba it was an error in package.json and has been fixed in 0.1.1 
I will close this issue. Thanks for letting me know.

**Comment by mploux** [comment]
The Yarn package is still empty :/

**Comment by ccwukong** [comment]
> The Yarn package is still empty :/

Hi, fixed. Thanks.
