### ISSUE TITLE
How to turn off webcam light after picture?

### ISSUE THREAD

**Issue by alimzhanovamir** [ccwukong/react-cam#6]

**Comment by sabuhish** [comment]
indeed, we are stuck at this point. @alimzhanovamir have you found a way to fix that?

The problem occurs right after taking a picture, light does not turn off, it keeps until you refresh the page.

**Comment by alimzhanovamir** [comment]
@sabuhish 
Solved the problem by accessing the video object via ref.
\
Add in onClick:
```
videoRef.current.camRef.current.srcObject.getTracks()[0].stop()
```
\
Example:
```import React, { Fragment, useRef } from 'react';
import ReactDOM from 'react-dom';
import { Camera } from 'react-cam';

function capture(imgSrc) {
  console.log(imgSrc);
}

const App = () => {
  const videoRef = useRef(null);
  return (
    <Fragment>
      <Camera
        showFocus={true}
        front={false}
        capture={capture}
        ref={videoRef }
        width="80%"
        height="auto"
        focusWidth="80%"
        focusHeight="60%"
        btnColor="white"
      />
      <button onClick={img => {
          camRef .current.capture(img)
         /* This will turn off the flow and the light bulb.*/
          videoRef.current.camRef.current.srcObject.getTracks()[0].stop()
      }}>Take image</button>
    </Fragment>
  );
};
ReactDOM.render(<App />, document.getElementById('root'));
```

**Comment by sabuhish** [comment]
> @sabuhish
> Solved the problem by accessing the video object via ref.
> 
> Add in onClick:
> 
> ```
> videoRef.current.camRef.current.srcObject.getTracks()[0].stop()
> ```
> 
> 
> Example:
> 
> ```
> import ReactDOM from 'react-dom';
> import { Camera } from 'react-cam';
> 
> function capture(imgSrc) {
>   console.log(imgSrc);
> }
> 
> const App = () => {
>   const videoRef = useRef(null);
>   return (
>     <Fragment>
>       <Camera
>         showFocus={true}
>         front={false}
>         capture={capture}
>         ref={videoRef }
>         width="80%"
>         height="auto"
>         focusWidth="80%"
>         focusHeight="60%"
>         btnColor="white"
>       />
>       <button onClick={img => {
>           camRef .current.capture(img)
>          /* This will turn off the flow and the light bulb.*/
>           videoRef.current.camRef.current.srcObject.getTracks()[0].stop()
>       }}>Take image</button>
>     </Fragment>
>   );
> };
> ReactDOM.render(<App />, document.getElementById('root'));
> ```
Thank you so much!!! I highly appreciate your help, this now works. It is amazing!! :) thanks, best wishes :)
